export { Base } from './Base'
export { Home } from './Home'
export { Training } from './Training'
export { Guide } from './Guide'
export { Error404 } from './Error404'
export { Settings } from './Settings'
export { Profile } from './Profile'
export { History } from './History'
